update grm

diff --git a/usr/local/sbin/grm b/usr/local/sbin/grm
--- a/usr/local/sbin/grm
+++ b/usr/local/sbin/grm
@@ -2,9 +2,22 @@
 #
 # grm - short command to search through Minimy python files 
 #
-cd $HOME/minimy
-fw="$HOME/minimy/framework"
-frameworkFiles="$fw/*py $fw/*/*py $fw/*/*/*py $fw/*/*/*/*py $fw/*/*/*/*/*py $fw/*/*/*/*/*/*py $fw/*/*/*/*/*/*/*py"
-mn="$HOME/minimy"
-srcFiles="$mn/*py $mn/bus/*py $mn/skills/*py $mn/skills/*/*py $mn/skills/*/*/*py"
-grep -n --color "$@" $frameworkFiles $srcFiles 2>/dev/null 
+if [ "$1" = "-h" -o "$1" = "" ]; then        # give help
+  echo "Name : grm search through Minimy python files"
+  echo "Usage: grm [-b baseDir ] pattern"
+  exit 1
+fi
+if [ $# -gt 0 -a "$1" = "-b" ]; then         # -b baseDir passed in
+  baseDir=$2
+  shift 2
+else
+  baseDir="$HOME/minimy"
+fi
+if [ ! -d $baseDir ]; then
+  echo "ERROR: directory $baseDir not found" 
+  exit 1
+fi
+cd $baseDir
+frameworkFiles="framework/*py framework/*/*py framework/*/*/*py framework/*/*/*/*py framework/*/*/*/*/*py framework/*/*/*/*/*/*py framework/*/*/*/*/*/*/*py"
+srcFiles="*py bus/*py $frameworkFiles skills/*py skills/*/*py skills/*/*/*py"
+grep -n "$@" $srcFiles 2>/dev/null | sed "s:^:$baseDir/:g"
