add startneon and stopneon, update grl, grn, lsenv, lslogs and rmlogs

diff --git a/usr/local/sbin/grn b/usr/local/sbin/grn
--- a/usr/local/sbin/grn
+++ b/usr/local/sbin/grn
@@ -4,14 +4,19 @@
 #
 if [ $# = 0 ]; then                        # no args passed
   echo "ERROR: no search pattern passed in"
-  echo "Usage: gro SEARCH_PATTERN"
+  echo "Usage: grn SEARCH_PATTERN"
   exit 1
 fi
 
-baseDir="$HOME/venv/lib/python3.*/site-packages"
-if [ ! -d $baseDir ]; then
-  echo "ERROR: Directory $baseDir not found" 
+pyDir=`ls -d $HOME/venv/lib/python3.*`
+if [ ! -d $pyDir ]; then
+  echo "ERROR: Python directory not found in $HOME/venv/lib/python3.* Is this a Neon box?"
   exit 1
+fi
+baseDir="$pyDir/site-packages"
+if [ ! -d $baseDir ]; then
+  echo "ERROR: Directory $baseDir not found. Is this a Neon box?"
+  exit 2
 fi
 
 echo
diff --git a/usr/local/sbin/rmlogs b/usr/local/sbin/rmlogs
--- a/usr/local/sbin/rmlogs
+++ b/usr/local/sbin/rmlogs
@@ -2,14 +2,26 @@
 #
 # rmlogs - remove OVOS log files 
 #
-logDir="$HOME/.local/state/mycroft"
+if [ -d $HOME/.local/state/neon ]; then      # assume this is a Neon box
+  logDir="$HOME/.local/state/neon"
+elif [ -d $HOME/.local/state/mycroft ]; then # assume OVOS
+  logDir="$HOME/.local/state/mycroft"
+else
+  echo "ERROR: could not find log dir in $HOME/.local/state/neon nor $HOME/.local/state/mycroft"
+  exit 1
+fi 
+stat $logDir/*.log >/dev/null 2>&1
+if [ $? != 0 ]; then                         # no log files found
+  echo "No log files found in log directory $logDir"
+  exit 3
+fi
 if [ "$1" != "-y" ]; then 
   echo "Remove all .log files in $logDir? (y/n)"
   read ans
   if [ "$ans" != "y" ]; then 
-    exit 1
+    exit 2
   fi
 fi  
 echo "Removing log files in $logDir ..."
-rm $logDir/*.log
+sudo rm $logDir/*.log
 
