update install1

diff --git a/usr/local/sbin/install1 b/usr/local/sbin/install1
--- a/usr/local/sbin/install1
+++ b/usr/local/sbin/install1
@@ -98,11 +98,11 @@ function runCmd
   cmd="$@"                                 # all args
 
   echo " " 
-  echo "Running: $cmd" 
-  eval $cmd 2>&1 
+  echo "Running: $cmd" | tee -a $outFile
+  eval $cmd 2>&1 | tee -a $outFile
   rc=$?
   if [ "$rc" != 0 ]; then                  # it failed
-    echo "ERROR: $cmd returned $rc" 
+    echo "ERROR: $cmd returned $rc - EXITING!!!" 
     exit 1
   else
     echo "Command was successful!" 
@@ -124,32 +124,41 @@ function installCoreqs
   fi
   echo "distro = $distro"
   pyVer=`python3 -V | awk '{print $2}' | awk -F. '{print $1 "." $2}'`
-  commonPackages="bind9-dnsutils cifs-utils curl jq locate lsof mpc mpd net-tools pandoc pipewire pipewire-audio-client-libraries pipewire-pulse python3 python3-pip python3-rpi.gpio python3-venv python${pyVer}-venv raspi-config wireplumber" 
+  commonPackages="bind9-dnsutils cifs-utils curl jq locate lsof mpc mpd net-tools pandoc python3 python3-pip python3-venv python${pyVer}-venv raspi-config" 
 
-  echo "Installing co-req packages ..."
+  echo "Installing co-req packages ..."| tee -a $outFile
   for nextPkg in $commonPackages; do  
     runCmd sudo apt-get --quiet install -y $nextPkg
   done
   
+  if [ "$platform" = "linux" ]; then       # not on an Nvidia GPU 
+    linuxOnly="pipewire pipewire-audio-client-libraries pipewire-pulse python3-rpi.gpio wireplumber"
+    for nextPkg in $linuxOnly; do
+      runCmd sudo apt-get --quiet install -y $nextPkg 
+    done
+  else                                     # assume Nvidia
+    echo "NOT installing pipewire and GPIO packages on Nvidia GPU" | tee -a $outFile
+  fi   
+
   if [ ! -f /etc/vim/vimrc.orig ]; then    # never copied original
     runCmd sudo cp /etc/vim/vimrc /etc/vim/vimrc.orig
   fi    
-  echo "Copying vimrc ..." 
+  echo "Copying vimrc ..." | tee -a $outFile
   runCmd sudo cp $HOME/ovos-tools/vimrc /etc/vim
   echo
   
-  echo "Adding groups to user pi ..." 
+  echo "Adding groups to user pi ..." | tee -a $outFile
   runCmd sudo usermod -a -G audio,video,dialout,kmem pi
-  echo "Adding groups to user mpd ..." 
-  runCmd sudo usermod -a -G pi users mpd
-  echo "Adding groups spi, i2c and gpio to /etc/groump ..." 
-  sudo groupadd -g 993 spi
-  sudo groupadd -g 994 i2c
-  sudo groupadd -g 993 gpio 
+  echo "Adding groups to user mpd ..." | tee -a $outFile
+  runCmd sudo usermod -a -G pi,users mpd
+  echo "Adding groups spi, i2c and gpio to /etc/groump ..." | tee -a $outFile
+  sudo groupadd -g 993 spi | tee -a $outFile
+  sudo groupadd -g 994 i2c | tee -a $outFile
+  sudo groupadd -g 993 gpio | tee -a $outFile
   echo
   
   # copy a .bash_profile specific to Neon, Minimy or OVOS 
-  echo "Copying .bash_profile ..." 
+  echo "Copying .bash_profile ..."  | tee -a $outFile
   if [ "$flavor" = "minimy" ]; then     
     runCmd cp $HOME/ovos-tools/minimy_profile $HOME/.bash_profile
   elif [ "$flavor" = "neon" ]; then     
@@ -161,7 +170,7 @@ function installCoreqs
   # turn default and vc4 audio off, don't disable monitor overscan
   cd /boot/firmware 
   if [ ! -f config.txt.orig ]; then
-    echo "Customizing boot parameters ..." 
+    echo "Customizing boot parameters ..."  | tee -a $outFile
     runCmd sudo cp config.txt config.txt.orig
     sudo sed -i -e 's/dtparam=audio=on/dtparam=audio=off\ndtparam=spi=off/g' \
                 -e 's/^disable_overscan/# disable_overscan/g' \
@@ -177,7 +186,7 @@ function installCoreqs
   fi  
   
   # vim - traditional defaults, mouse works
-  echo "Removing annoying autoindent from vim ..." 
+  echo "Removing annoying autoindent from vim ..."  | tee -a $outFile
   if [ ! -d $HOME/.vim ]; then
     runCmd mkdir $HOME/.vim 
   fi  
@@ -185,18 +194,18 @@ function installCoreqs
   echo "set noautoindent" >> vimrc
   echo "set nocindent" >> vimrc
   echo "set nosmartindent" >> vimrc
-  # echo "set indentexpr=" >> vimrc
+  echo "set mouse=r" >> vimrc
   
-  # rsyslog can send a flood of kernel messages
-  if [ -f /etc/rsyslog.conf -a ! -f /etc/rsyslog.conf.orig ]; then 
-    echo "preventing rsyslogd from making log message storms ..." 
-    runCmd sudo cp /etc/rsyslog.conf /etc/rsyslog.conf.orig
-    sudo sed -i 's/^module(load="imklog"/# module(load="imklog"/g' /etc/rsyslog.conf
-  fi
+  # rsyslog can send a flood of kernel messages - hope this has been fixed by now...
+  # if [ -f /etc/rsyslog.conf -a ! -f /etc/rsyslog.conf.orig ]; then 
+  #   echo "preventing rsyslogd from making log message storms ..." 
+  #   runCmd sudo cp /etc/rsyslog.conf /etc/rsyslog.conf.orig
+  #   sudo sed -i 's/^module(load="imklog"/# module(load="imklog"/g' /etc/rsyslog.conf
+  # fi
   
   # configure mpd
   if [ -f /etc/mpd.conf -a ! -f /etc/mpd.conf.orig ]; then # no backup has been made
-    echo "Making backup of /etc/mpd.conf" 
+    echo "Making backup of /etc/mpd.conf"  | tee -a $outFile 
     runCmd sudo cp /etc/mpd.conf /etc/mpd.conf.orig 
   fi
   if [ ! -d /var/log/mpd ]; then           # no mpd log dir
@@ -204,51 +213,57 @@ function installCoreqs
     sudo chown $USER /var/log/mpd
     sudo touch /var/log/mpd/mpd.log 
   fi
-  echo "Copying sample mpd.conf file to /etc" 
+  echo "Copying sample mpd.conf file to /etc" | tee -a $outFile 
   runCmd sudo cp ~/ovos-tools/mpd.conf /etc # copy sample 
-  echo "Changing permissons of /etc/mpd.conf" 
+  echo "Changing permissons of /etc/mpd.conf" | tee -a $outFile 
   runCmd sudo chmod 644 /etc/mpd.conf  
-  echo "Setting mpd to start at boot time" 
+  echo "Setting mpd to start at boot time" | tee -a $outFile 
   runCmd systemctl --user enable mpd         # start mpd at boot
-  echo "Setting pipewire and pipewire-pulse to start at boot time..."
-  runCmd systemctl --user enable pipewire pipewire-pulse
-  echo "Disabling bluetooth ..."
+  if [ "$platform" = "linux" ]; then         # Linux needs pipewire
+    echo "Setting pipewire and pipewire-pulse to start at boot time..." | tee -a $outFile
+    runCmd systemctl --user enable pipewire pipewire-pulse
+  fi
+  echo "Disabling bluetooth ..." | tee -a $outFile
   runCmd sudo systemctl disable bluetooth.service
 
   # configure USB hot plug to mount USB drive over /mnt/usb
   runCmd sudo cp ~/ovos-tools/99-mount-usb.rules /etc/udev/rules.d
   runCmd sudo cp ~/ovos-tools/usb-mount@.service /etc/systemd/system
   runCmd sudo cp ~/ovos-tools/usb-mount.sh /root 
-
-  # configure the gateway to be the DNS resolver
-  # DNSstmt=`grep ^DNS /etc/systemd/resolved.conf`
-  # if [ ${#DNSstmt} = 0 ]; then             # DNS resolver not found
-  #   gw=`ip route | head -1 | awk '{print $3}'` # get the gatway
-  #   numDots=`echo $gw | awk -F'.' '{print NF}'` # check that it is dotted decimal
-  #   if [ "$numDots" != 4 ]; then           # error
-  #     echo "ERROR: $gw does not appear to be an IPv4 address"
-  #     exit 1
-  #   fi  
-  #   echo "Setting $gw to DNS resolver..."
-  #   echo "DNS=$gw" | sudo tee -a /etc/systemd/resolved.conf
-  #   rc=$?
-  #   if [ "$rc" != 0 ]; then
-  #     echo "ERROR: echo DNS=$gw | sudo tee -a /etc/systemd/resolved.conf returned $rc"	  
-  #   fi  
-  #   runCmd sudo systemctl restart systemd-resolved
-  # else
-  #   echo "Found: $DNSstmt in /etc/systemd/resolved.conf"
-  # fi
+ 
+  # configure network drive to mount over /mnt/share
+  echo "Configuring network drive to mount over /mnt/share ..." | tee -a $outFile
+  if [ ! -d ~/mpd ]; then                  # create a mpd dir in home directory
+    mkdir ~/mpd;
+  fi
+  if [ ! -f /etc/fstab.orig ]; then        # make a backup copy and add a line
+    sudo cp /etc/fstab /etc/fstab.orig
+    echo "//LS210D7A7.lan/share   /mnt/share    cifs    user=mike,password=sawdust5,vers=1.0 0 0" | sudo tee -a /etc/fstab
+  fi
+  if [ ! -d /mnt/share ]; then             # create directory
+    sudo mkdir /mnt/share
+    sudo chgrp users /mnt/share
+    sudo chmod 777 /mnt/share
+  fi
+  grep "/mnt/share" /etc/mtab >/dev/null 2>&1
+  if [ $? != 0 ]; then                     # dir is not mounted
+    runCmd sudo mount /mnt/share
+  fi
  }                                         # installCoreqs()
 
 # main()
 flavor="minimy"                            # minimy, neon or ovos
+if [ -d /usr/share/doc/nvidia-jetpack ]; then # on an Nvidia GPU 
+  platform="nvidia"
+else                                       # assume Raspberry Pi
+  platform="raspi"
+fi
 timeStamp=`date +"%y-%m-%d-%H-%M-%S"`   
 outFile="$HOME/$timeStamp-install1.out"    # output file
 parseArgs $@
 checkOvosTools                             # verify ovos-tools is installed
 echo "Running install1 on $timeStamp to configure $flavor ..." > $outFile # create a new log file
-installCoreqs | tee -a $outFile            # do the work
+installCoreqs                              # do the work
 let min=$SECONDS/60
 let sec=$SECONDS%60
 if [ $sec -lt 10 ]; then                   # add a leading 0
