add installneon

diff --git a/usr/local/sbin/installneon b/usr/local/sbin/installneon
--- a/usr/local/sbin/installneon
+++ b/usr/local/sbin/installneon
@@ -1,11 +1,10 @@
 #!/bin/bash
 #
-# installneon - Install the Neon personal voice assistant
+# installneon - Install packages, etc. for the Neon personal voice assistant
 #
 #+--------------------------------------------------------------------------+
 function usage
-# Parse arguments
-# Args: All arguments passed into script
+# Give help 
 #+--------------------------------------------------------------------------+
  {
   : SOURCE: ${BASH_SOURCE}
@@ -17,10 +16,8 @@ function usage
   echo ""
   echo "OPTIONS:"
   echo "  -h|--help         Give help (this screen)"
-  echo "  -m|--mike99mac    Try Mike Mac's experimental approach"
   echo "  -v|--verbose      Increase verbosity"
   echo "  -x|--debug        Print commands and arguments as they are executed"
-  echo "  -y|--yes          Do not prompt to remove old venv"
   exit 51
  }                                         # usage()
 
@@ -45,9 +42,6 @@ function parseArgs
       -x|--debug)                          # turn trace on
          set -vx
          ;;
-      -y|--yes)                            # do not prompt
-         yes="yes"
-         ;;
       *)
         echo "ERROR: Unrecognized argument: $1"
         usage
@@ -65,64 +59,42 @@ function runCmd
   : SOURCE: ${BASH_SOURCE}
   : STACK:  ${FUNCNAME[@]}
 
-  local timeStamp=`date +"%y-%m-%d-%H:%M:%S"`      # YY-MM-DD-HH:MM:SS
+  local timeStamp=`date +"%y-%m-%d-%H-%M-%S"` 
   cmd="$@"                                 # get all args
-  echo "$timeStamp - Running: $cmd ..." | tee -a $logFile # show the command and send to output file
+  echo "$timeStamp - Running: $cmd ..."    # show the command and send to output file
   eval $cmd >> $logFile 2>&1               # run the command
   rc=$?
   if [ "$rc" != 0 ]; then                  # it failed
-    echo "ERROR: $cmd returned $rc" | tee -a $logFile
+    echo "ERROR: $cmd returned $rc" 
     exit 1
   fi
  }                                         # runCmd()
 
 #+--------------------------------------------------------------------------+
-function installWithGit 
-# install package with git clone
-# Arg 1: the URL to install
+function addGroupsUsers
+# Configure docker group and user
 #+--------------------------------------------------------------------------+
  {
   : SOURCE: ${BASH_SOURCE}
   : STACK:  ${FUNCNAME[@]}
 
-  local thePkg="$@"
-  let curPkg=$curPkg+1
-  echo | tee -a $logFile
-  echo "Installing package $curPkg of $pkgCnt: $thePkg..." | tee -a $logFile
-  runCmd git clone https://github.com/OpenVoiceOS/$thePkg 
- }                                         # installWithGit()
-
-#+--------------------------------------------------------------------------+
-function installWithPip
-# install package with "pip install"
-# Arg 1: the URL to install
-#+--------------------------------------------------------------------------+
- {
-  : SOURCE: ${BASH_SOURCE}
-  : STACK:  ${FUNCNAME[@]}
-
-  local thePkg="$@"
-  let curPkg=$curPkg+1
-  echo | tee -a $logFile
-  echo "Installing package $curPkg of $pkgCnt: $thePkg..." | tee -a $logFile
-  runCmd pip install $thePkg 
- }                                         # installWithPip()
-
-#+--------------------------------------------------------------------------+
-function installWithGitPip 
-# install package with "pip install git+URL"
-# Arg 1: the URL to install
-#+--------------------------------------------------------------------------+
- {
-  : SOURCE: ${BASH_SOURCE}
-  : STACK:  ${FUNCNAME[@]}
-
-  local thePkg="$@"
-  let curPkg=$curPkg+1
-  echo | tee -a $logFile
-  echo "Installing package $curPkg of $pkgCnt: $thePkg..." | tee -a $logFile
-  runCmd pip install git+https://github.com/OpenVoiceOS/$thePkg 
- }                                         # installWithGitPip()
+  getent group docker >/dev/null 2>&1
+  if [ $? != 0 ]; then                     # group docker does not exist
+    sudo groupadd -g $dockerGID docker
+    if [ $? != 0 ]; then                   # cannot proceed
+      echo "ERROR: sudo groupadd -g $dockerGID docker returned $? - exiting"
+      exit 1
+    fi
+    id docker >/dev/null 2>&1
+    if [ $? != 0 ]; then                     # user docker does not exist
+      sudo useradd -g $dockerGID -u $dockerUID docker
+      if [ $? != 0 ]; then                   # cannot proceed
+        echo "ERROR: sudo useradd -g $dockerGID -u $dockerUID docker returned $? - exiting"
+        exit 1
+      fi
+    fi
+  fi
+ }                                         # addGroupsUsers()
 
 #+--------------------------------------------------------------------------+
 function installNeon
@@ -132,58 +104,21 @@ function installNeon
   : SOURCE: ${BASH_SOURCE}
   : STACK:  ${FUNCNAME[@]}
 
-  local date=`date`
-  echo "Running installneon ..." | tee -a $logFile
-  if [ -d $HOME/.venvs ]; then                 #  directory exists
-    if [ "$1" != "-y" ]; then
-      echo -n "$HOME/.venvs directory exists - do you want to remove it and rebuild? (y/n) "
-      read ans
-      if [ "$ans" != y -a "$ans" != Y ]; then
-        exit 4
-      fi
-    fi
-    echo "removing $HOME/.venvs directory ..."
-    sudo /usr/bin/rm -fr $HOME/.venvs | tee -a $logFile
-    if [ $? != 0 ]; then
-      echo "/usr/bin/rm -fr $HOME/.venvs returned $? trying again ..."
-      /usr/bin/rm -fr $HOME/.venvs | tee -a $logFile
-      if [ $? != 0 ]; then
-        echo "/usr/bin/rm -fr $HOME/.venvs failed again with $? ... punt! ..." | tee -a $logFile
-        exit 5
-      fi
-    fi
-  fi
-
-  # useInstaller
-
-  # for longer main memory life, write Neon logs to a tmpfs
-  local mountFile="home-pi-.local-state-mycroft.mount"
-  if [ ! -f /etc/systemd/system/$mountFile  ]; then # mount file has not been copied
-    local srcFile="$HOME/ovos-tools/$mountFile"
-    if [ ! -f $srcFile ]; then             # not expected
-      echo "ERROR: mount file $srcFile not found"
-      exit 1
-    fi
-    echo "Copying and enabling mount file $mountFile ..." | tee -a $outFile
-    runCmd sudo cp $srcFile /etc/systemd/system
-    runCmd sudo systemctl daemon-reload 
-    runCmd sudo systemctl enable $mountFile 
-    runCmd sudo systemctl start $mountFile 
-  fi
+  addGroupsUsers                           # add group and user 'docker'
+  sudo apt install -y docker docker-compose
  }                                         # installNeon()
 
 # main()
 curPkg=0                                   # current package being installed
-pkgCnt=0                                   # of packages
+dockerUID=1017                             # change if UID 1017 is taken
+dockerGID=1017                             # change if GID 1017 is taken
 verbose=1                                  # verbosity
-yes="no"
 
 parseArgs $@                               # parse arguments
-timeStamp=`date +"%y-%m-%d-%H:%M:%S"`      # YY-MM-DD-HH:MM:SS
+timeStamp=`date +"%y-%m-%d-%H-%M-%S"`      
 logFile="$HOME/$timeStamp-installneon.out" # output file
-pkgCnt=`wc -l $HOME/ovos-tools/*.packages | tail -1 | awk '{print $1}'`
-
-installNeon $@                             # do the work
+echo "Running installneon ..." | tee $logFile
+installNeon $@ | tee -a $logFile 2>&1     # send output to log file
 let min=$SECONDS/60                        # show time spent installing
 let sec=$SECONDS%60
 if [ $sec -lt 10 ]; then                   # add a leading 0
