update lsenv and installovos

diff --git a/usr/local/sbin/installovos b/usr/local/sbin/installovos
--- a/usr/local/sbin/installovos
+++ b/usr/local/sbin/installovos
@@ -205,9 +205,9 @@ function installOVOS
   local pyVer=`python --version | awk '{print $2}' | awk -F. '{print $1 "." $2}'`
   cd $HOME/.venvs/ovos/lib/python$pyVer/site-packages
 
-  echo | tee -a $logFile
-  echo "Cloning ovos-core ..." | tee -a $logFile
-  runCmd git clone https://github.com/OpenVoiceOS/ovos-core
+# echo | tee -a $logFile
+# echo "Cloning ovos-core ..." | tee -a $logFile
+# runCmd git clone https://github.com/OpenVoiceOS/ovos-core
   
   echo | tee -a $logFile
   echo "Installing packages with apt-get ..." | tee -a $logFile
@@ -224,7 +224,7 @@ function installOVOS
 
   echo | tee -a $logFile
   echo "Installing ovos-core ..." | tee -a $logFile
-  runCmd "pip install ovos-core[all]"
+  runCmd "pip install ovos-core"
 
   # some packages are "git clone"d, some just use pip and others need pip+git
   local nextPkg
@@ -266,6 +266,20 @@ function installOVOS
   for nextService in ovos-messagebus ovos-phal ovos-audio ovos-core ovos-listener ovos-media; do
     copyServiceFile $nextService user
   done
+
+  # to lengthen the life of the memory device, write logs to a tmpfs
+  local mountFile="home-pi-.local-state-mycroft.mount"
+  if [ ! -f /etc/systemd/system/$mountFile  ]; then # mount file has not been copied
+    local srcFile="$HOME/ovos-tools/$mountFile"
+    if [ ! -f $srcFile ]; then             # not expected
+      echo "ERROR: mount file $srcFile not found"
+      exit 1
+    fi
+    echo "Copying mount file $mountFile ..." | tee -a $outFile
+    runCmd sudo cp $srcFile /etc/systemd/system
+    runCmd sudo systemctl daemon-reload 
+    runCmd sudo systemctl enable $mountFile 
+  fi
  }                                         # installOVOS()
 
 # main()
