update installovos

diff --git a/usr/local/sbin/installovos b/usr/local/sbin/installovos
--- a/usr/local/sbin/installovos
+++ b/usr/local/sbin/installovos
@@ -17,6 +17,7 @@ function usage
   echo ""
   echo "OPTIONS:"
   echo "  -h|--help         Give help (this screen)"
+  echo "  -m|--mike99mac    Try Mike Mac's experimental approach"
   echo "  -v|--verbose      Increase verbosity"
   echo "  -x|--debug        Print commands and arguments as they are executed"
   echo "  -y|--yes          Do not prompt to remove old venv"
@@ -37,6 +38,9 @@ function parseArgs
     case "$1" in
       -h|--help)
         usage
+        ;;
+      -m|--mike99mac)                      # try Mike Mac's experimental code
+        installType="mike99mac"
         ;;
       -v|--verbose)
         verbose=2
@@ -64,8 +68,9 @@ function runCmd
   : SOURCE: ${BASH_SOURCE}
   : STACK:  ${FUNCNAME[@]}
 
+  local timeStamp=`date +"%y-%m-%d-%H:%M:%S"`      # YY-MM-DD-HH:MM:SS
   cmd="$@"                                 # get all args
-  echo "Running: $cmd ..." | tee -a $logFile # show the command and send to output file
+  echo "$timeStamp - Running: $cmd ..." | tee -a $logFile # show the command and send to output file
   eval $cmd >> $logFile 2>&1               # run the command
   rc=$?
   if [ "$rc" != 0 ]; then                  # it failed
@@ -73,6 +78,38 @@ function runCmd
     exit 1
   fi
  }                                         # runCmd()
+
+#+--------------------------------------------------------------------------+
+function useInstaller
+# Install OVOS with goldyfruit's installer.sh 
+#+--------------------------------------------------------------------------+
+ {
+  : SOURCE: ${BASH_SOURCE}
+  : STACK:  ${FUNCNAME[@]}
+
+  # first be sure scenario.yaml is present to automate the install
+  local configDir="$HOME/.config/ovos-installer"
+  local configFile="$configDir/scenario.yaml"
+
+  if [ ! -d $configDir ]; then             # config directory does not exist
+    runCmd mkdir -p $configDir
+  fi
+
+  if [ ! -f $configFile ]; then            # config file does not exist
+    if [ ! -f $HOME/ovos-tools/scenario.yaml ]; then # not expected
+      echo "ERROR: unexpected $HOME/ovos-tools/scenario.yaml not found - is ovos-tools installed?"
+      exit 1
+    fi
+    runCmd cp $HOME/ovos-tools/scenario.yaml $configDir
+  fi 
+
+  # run the installer
+  cd                                       # start in the home directory
+  runCmd curl -s https://raw.githubusercontent.com/OpenVoiceOS/ovos-installer/main/installer.sh -o installer.sh
+  runCmd chmod +x installer.sh 
+  echo "Installing OVOS with install.sh ... this will take some time ... Log File: $logFile" 
+  runCmd sudo ./installer.sh
+ }                                         # useInstaller()
 
 #+--------------------------------------------------------------------------+
 function installWithGit 
@@ -160,34 +197,13 @@ function copyServiceFile
  }                                         # copyServiceFile()
 
 #+--------------------------------------------------------------------------+
-function installOVOS
-# Do the work to install ovos-core and all ancillary packages into a venv 
+function useMike99mac
+# Install OVOS with goldyfruit's installer.sh
 #+--------------------------------------------------------------------------+
  {
   : SOURCE: ${BASH_SOURCE}
   : STACK:  ${FUNCNAME[@]}
 
-  local date=`date`
-  echo "Running installovos on $date ..." | tee -a $logFile
-  if [ -d $HOME/.venvs ]; then                 #  directory exists
-    if [ "$1" != "-y" ]; then 
-      echo -n "$HOME/.venvs directory exists - do you want to remove it and rebuild? (y/n) "
-      read ans
-      if [ "$ans" != y -a "$ans" != Y ]; then
-        exit 4
-      fi
-    fi
-    echo "removing $HOME/.venvs directory ..."
-    /usr/bin/rm -fr $HOME/.venvs | tee -a $logFile
-    if [ $? != 0 ]; then 
-      echo "/usr/bin/rm -fr $HOME/.venvs returned $? trying again ..."
-      /usr/bin/rm -fr $HOME/.venvs | tee -a $logFile
-      if [ $? != 0 ]; then 
-        echo "/usr/bin/rm -fr $HOME/.venvs failed again with $? ... punt! ..." | tee -a $logFile
-        exit 5
-      fi
-    fi	    
-  fi
 
   if [ ! -f $HOME/ovos-tools/ovos.git.packages  ]; then
     echo "ERROR: $HOME/ovos-tools/ovos.git.packages not found - is ovos-tools installed?" | tee -a $logFile
@@ -205,10 +221,6 @@ function installOVOS
   local pyVer=`python --version | awk '{print $2}' | awk -F. '{print $1 "." $2}'`
   cd $HOME/.venvs/ovos/lib/python$pyVer/site-packages
 
-# echo | tee -a $logFile
-# echo "Cloning ovos-core ..." | tee -a $logFile
-# runCmd git clone https://github.com/OpenVoiceOS/ovos-core
-  
   echo | tee -a $logFile
   echo "Installing packages with apt-get ..." | tee -a $logFile
   runCmd sudo apt-get install -y build-essential python3-dev swig libssl-dev libfann-dev libpulse-dev libasound2-dev mpg123 portaudio19-dev python3-pyaudio liblapack-dev libopenblas-dev flac
@@ -216,11 +228,6 @@ function installOVOS
   echo | tee -a $logFile
   echo "Installing wheel with pip install ..." | tee -a $logFile
   runCmd pip install wheel                 # wheel needs to be in place before other packages 
-
-# moved to install1
-#  echo | tee -a $logFile
-# echo "Installing other non-ovos packages with pip install ..." | tee -a $logFile
-# runCmd pip install silero tornado 
 
   echo | tee -a $logFile
   echo "Installing ovos-core ..." | tee -a $logFile
@@ -266,8 +273,49 @@ function installOVOS
   for nextService in ovos-messagebus ovos-phal ovos-audio ovos-core ovos-listener ovos-media; do
     copyServiceFile $nextService user
   done
+ }                                         # useMike99mac()
 
-  # to lengthen the life of the memory device, write logs to a tmpfs
+#+--------------------------------------------------------------------------+
+function installOVOS
+# Do the work to install ovos-core and all ancillary packages into a venv
+#+--------------------------------------------------------------------------+
+ {
+  : SOURCE: ${BASH_SOURCE}
+  : STACK:  ${FUNCNAME[@]}
+
+  local date=`date`
+  echo "Running installovos ..." | tee -a $logFile
+  if [ -d $HOME/.venvs ]; then                 #  directory exists
+    if [ "$1" != "-y" ]; then
+      echo -n "$HOME/.venvs directory exists - do you want to remove it and rebuild? (y/n) "
+      read ans
+      if [ "$ans" != y -a "$ans" != Y ]; then
+        exit 4
+      fi
+    fi
+    echo "removing $HOME/.venvs directory ..."
+    sudo /usr/bin/rm -fr $HOME/.venvs | tee -a $logFile
+    if [ $? != 0 ]; then
+      echo "/usr/bin/rm -fr $HOME/.venvs returned $? trying again ..."
+      /usr/bin/rm -fr $HOME/.venvs | tee -a $logFile
+      if [ $? != 0 ]; then
+        echo "/usr/bin/rm -fr $HOME/.venvs failed again with $? ... punt! ..." | tee -a $logFile
+        exit 5
+      fi
+    fi
+  fi
+
+  # perform one of two install types
+  if [ "$installType" = "goldyfruit" ]; then # use installer.sh
+    useInstaller
+  elif [ "$installType" = "mike99mac" ]; then # use Mike's code
+    useMike99mac
+  else
+    echo "ERROR: unexpected: installType = $installType"
+    exit 1
+  fi
+
+  # for longer main memory life, write OVOS logs to a tmpfs
   local mountFile="home-pi-.local-state-mycroft.mount"
   if [ ! -f /etc/systemd/system/$mountFile  ]; then # mount file has not been copied
     local srcFile="$HOME/ovos-tools/$mountFile"
@@ -284,6 +332,7 @@ function installOVOS
 
 # main()
 curPkg=0                                   # current package being installed
+installType="goldyfruit"                   # install code to use - default - installer.sh
 pkgCnt=0                                   # of packages
 verbose=1                                  # verbosity
 yes="no"
@@ -299,8 +348,7 @@ let sec=$SECONDS%60
 if [ $sec -lt 10 ]; then                   # add a leading 0
   sec="0$sec"
 fi
-echo | tee -a $logFile
 echo "Successfully installed OVOS in $min:$sec" | tee -a $logFile
 echo
-echo "Log file of all operations: $logFile"
+echo "Log file: $logFile"
 
