update gro, lsenv and installovos

diff --git a/usr/local/sbin/installovos b/usr/local/sbin/installovos
--- a/usr/local/sbin/installovos
+++ b/usr/local/sbin/installovos
@@ -118,7 +118,7 @@ function installWithGitPip
   local thePkg="$@"
   let curPkg=$curPkg+1
   echo
-  echo "installing package $curPkg of $pkgCnt: $thePkg..." | tee -a $outFile
+  echo "Installing package $curPkg of $pkgCnt: $thePkg..." | tee -a $outFile
   runCmd pip install git+https://github.com/OpenVoiceOS/$thePkg 
  }                                         # installWithGitPip()
 
@@ -135,18 +135,23 @@ function copyServiceFile
   local serviceName="$1"
   local serviceType=$2    
   local serviceFQDN="$HOME/ovos-tools/$1.service"
+  local systemdDir="$HOME/.config/system/user"
 
   if [ ! -f $serviceFQDN ]; then
     echo "ERROR: service file $serviceFQDN not found - is ovos-tools installed?"
     exit 2
   fi    
+  if [ ! -d $systemdDir ]; then            # systemd directory does not exist
+    local cmd="mkdir -p $HOME/.config/system/user"
+    runCmd $cmd
+  fi
 
   if [ "$serviceType" = root ]; then       # copy to systemd system directory
     runCmd sudo cp $serviceFQDN /etc/systemd/system
     runCmd sudo systemctl enable $serviceName 
     runCmd sudo systemctl start $serviceName 
   elif [ "$serviceType" = user ]; then     # copy to systemd user directory
-    runCmd sudo cp $serviceFQDN /etc/systemd/user
+    runCmd sudo cp $serviceFQDN $systemdDir
     runCmd systemctl --user enable $serviceName
     runCmd systemctl --user start $serviceName
   else                                     # not expected
@@ -164,7 +169,7 @@ function installOVOS
   : STACK:  ${FUNCNAME[@]}
 
   local date=`date`
-  echo "Running installovos on $date ..." 
+  echo "Running installovos on $date ..." | tee -a $outFile
   echo 
   if [ -d ~/.venvs ]; then                 #  directory exists
     if [ "$1" != "-y" ]; then 
@@ -180,14 +185,14 @@ function installOVOS
       echo "/usr/bin/rm -fr $HOME/.venvs returned $? trying again ..."
       /usr/bin/rm -fr $HOME/.venvs | tee -a $outFile
       if [ $? != 0 ]; then 
-        echo "/usr/bin/rm -fr $HOME/.venvs failed again with $? ... punt! ..."
+        echo "/usr/bin/rm -fr $HOME/.venvs failed again with $? ... punt! ..." | tee -a $outFile
         exit 5
       fi
     fi	    
   fi
 
   if [ ! -f $HOME/ovos-tools/ovos.git.packages  ]; then
-    echo "ERROR: $HOME/ovos-tools/ovos.git.packages not found - is ovos-tools installed?"
+    echo "ERROR: $HOME/ovos-tools/ovos.git.packages not found - is ovos-tools installed?" | tee -a $outFile
   fi
   
   echo | tee -a $outFile
@@ -223,19 +228,19 @@ function installOVOS
 
   # some packages are "git clone"d, some just use pip and others need pip+git
   local nextPkg
-  echo "Installing ovos packages with git ..."
+  echo "Installing ovos packages with git ..." | tee -a $outFile
   local gitPkgs=`cat $HOME/ovos-tools/ovos.git.packages | xargs`
   for nextPkg in $gitPkgs; do
     installWithGit $nextPkg
   done
 
-  echo "Installing ovos packages with pip ..."
+  echo "Installing ovos packages with pip ..." | tee -a $outFile
   local pipPkgs=`cat $HOME/ovos-tools/ovos.pip.packages | xargs`
   for nextPkg in $pipPkgs; do
     installWithPip $nextPkg
   done
 
-  echo "Installing ovos packages with install ..."
+  echo "Installing ovos packages with install ..." | tee -a $outFile
   local pipPkgs=`cat $HOME/ovos-tools/ovos.pip+git.packages | xargs`
   for nextPkg in $pipPkgs; do
     installWithGitPip $nextPkg
diff --git a/usr/local/sbin/lsenv b/usr/local/sbin/lsenv
--- a/usr/local/sbin/lsenv
+++ b/usr/local/sbin/lsenv
@@ -60,6 +60,20 @@ function parseArgs()
  }                                         # parseArgs()
 
 #+--------------------------------------------------------------------------+
+function verboseMsg()
+# Print message when in verbose mode
+# Args: message
+#+--------------------------------------------------------------------------+
+ {
+  : SOURCE: ${BASH_SOURCE}
+  : STACK:  ${FUNCNAME[@]}
+
+  if [ "$verbose" -gt 1 ]; then    
+    echo "$@"
+  fi
+ }                                         # verboseMsg()
+
+#+--------------------------------------------------------------------------+
 function listService()
 # List the status of one service 
 # Arg 1: service to list
@@ -69,30 +83,47 @@ function listService()
   : STACK:  ${FUNCNAME[@]}
 
   local theService=$1
+  local cmd
+  local nextService
   local procs
 
-  echo "Status of $theService:"
-  local tempFile=`mktemp`
-  /usr/sbin/service $theService status > $tempFile 2>/dev/null
-  local activeLine=`grep "active (running)" $tempFile 2>/dev/null`
-  if [ ${#activeLine} != 0 ]; then         # found "active (running)"
-    echo " -) $theService is running as a service:"
-    echo "$activeLine" | sed 's/^ //g'
-    if [ "$theService" = pulseaudio ]; then # always show pulse processes
-      echo "    pulseaudio processes:"
-      ps -ef | grep $theService | grep -v grep | sed 's/^/    /g'
-    fi
+  if [ "$theService" = ovos ]; then        # check OVOS services
+    echo "OVOS services:"
+    cmd="/usr/bin/systemctl status ovos-phal-admin" # the one service running as root
+    echo -n "  ovos-phal-admin: "
+    verboseMsg "Running: $cmd" 
+    cmdOut=`$cmd` 
+    echo "$cmdOut" | egrep 'active|inactive|activating|failed|exited' 
+    verboseMsg "$cmdOut"
+
+    # query the user based services
+    for nextService in ovos-audio ovos-core ovos-listener ovos-media ovos-messagebus; do
+      cmd="/usr/bin/systemctl --user status $nextService"
+      echo -n "  $nextService: "
+      verboseMsg "Running: $cmd" 
+      cmdOut=`eval $cmd` 
+      printf "$cmdOut" | egrep 'active|inactive|activating|failed|exited' 
+      verboseMsg "$cmdOut"
+    done 
   else
-    echo " -) WARNING: $theService is not running as a service ... checking for processes ..."
-    procs=`ps -ef | grep $theService | grep -v grep`
-    if [ ${#procs} != 0 ]; then            # matching process
-      echo "    Found matching $theService processes:"
-      echo "$procs" | sed 's/^/    /g'
-    else
-      echo "    WARNING: $theService does not appear to be running"
-    fi  
+    echo "$theService service:"
+    cmd="/usr/bin/systemctl status $theService"
+    $cmd | grep "active (running)" 
+    if [ $? != 0 ]; then                   # did not find "active (running)"
+      echo "  WARNING: $theService is not running as a service ... checking for processes ..."
+      procs=`ps -ef | grep $theService | grep -v grep`
+      if [ "$theService" = pulseaudio ]; then # always show pulse processes
+        echo "    pulseaudio processes:"
+        ps -ef | grep $theService | grep -v grep | sed 's/^/    /g'
+      fi
+      if [ ${#procs} != 0 ]; then            # matching process
+        echo "    Found matching $theService processes:"
+        echo "$procs" | sed 's/^/    /g'
+      else
+        echo "    WARNING: $theService does not appear to be running"
+      fi  
+    fi
   fi	  
-  /usr/bin/rm $tempFile                    # remove output file 
   echo $dashes 
  }                                         # listService()
 
@@ -190,13 +221,10 @@ function doList()
   if [ ${#options} = 0 ]; then 
     clear                                  # clear the screen
   fi
-  ps -ef | grep -v grep | grep ovos_PHAL >/dev/null
-  if [ $? = 0 ]; then                      # looks like OVOS is running 
-    service="ovos"
-    listService bin/ovos  
-  fi
-  listService pulseaudio                   # alwasy check for pulse
-  
+  listService ovos
+  listService pulseaudio                   # always check for pulse
+  listService mpd 
+
   distro=`grep ^PRETTY /etc/os-release | awk -F'"' '{print $2}'` # get the pretty name
   OVOSver=`ovosver 2>/dev/null`
   if [ ${#OVOSver} = 0 ]; then             # did not get version
