update lsenv for OVOS

diff --git a/usr/local/sbin/lsenv b/usr/local/sbin/lsenv
--- a/usr/local/sbin/lsenv
+++ b/usr/local/sbin/lsenv
@@ -11,7 +11,7 @@ function usage()
   : STACK:  ${FUNCNAME[@]}
 
   echo "Name: lsenv - List information about the OVOS environment" 
-  echo "Usage: lsenv [OPTIONS] [noclear]" 
+  echo "Usage: lsenv [OPTIONS]" 
   echo "Where: noclear      Does not clear the screen first"
   echo ""
   echo "OPTIONS:"
@@ -36,6 +36,9 @@ function parseArgs()
       -h|--help)
         usage
         ;;
+      -n|--noclear)                        # do not clear the screen
+        clear="no"
+        ;;
       -v|--verbose) 
         verbose=2
         ;;
@@ -43,16 +46,8 @@ function parseArgs()
          set -vx
          ;;
       *)
-        if [ ${#options} != 0 ]; then      # PATTERN already passed
-          echo "ERROR: Too many arguments: $1"
-          usage
-        else
-          options=$1
-          if [ "$options" != noclear ]; then
-	    echo "ERROR: Too many arguments: $1"
-	    usage 
-          fi
-        fi
+        echo "ERROR: Too many arguments: $1"
+        usage
         ;;
     esac
     shift
@@ -77,54 +72,49 @@ function verboseMsg()
 function listService()
 # List the status of one service 
 # Arg 1: service to list
+# Arg 2: "root" or "user" service
 #+--------------------------------------------------------------------------+
  {
   : SOURCE: ${BASH_SOURCE}
   : STACK:  ${FUNCNAME[@]}
 
   local theService=$1
+  local serviceType=$2
+
   local cmd
-  local nextService
-  local procs
+  local status 
+  # RED="\e[31m"              print in colors
+  # GREEN="\e[32m"
+  # YELLOW="\e[33m"
 
-  if [ "$theService" = ovos ]; then        # check OVOS services
-    echo "OVOS services:"
-    cmd="/usr/bin/systemctl status ovos-phal-admin" # the one service running as root
-    echo -n "  ovos-phal-admin: "
-    verboseMsg "Running: $cmd" 
-    cmdOut=`$cmd` 
-    echo "$cmdOut" | egrep 'active|inactive|activating|failed|exited' 
-    verboseMsg "$cmdOut"
-
-    # query the user based services
-    for nextService in ovos-audio ovos-core ovos-listener ovos-media ovos-messagebus; do
-      cmd="/usr/bin/systemctl --user status $nextService"
-      echo -n "  $nextService: "
-      verboseMsg "Running: $cmd" 
-      cmdOut=`eval $cmd` 
-      printf "$cmdOut" | egrep 'active|inactive|activating|failed|exited' 
-      verboseMsg "$cmdOut"
-    done 
-  else
-    echo "$theService service:"
+  if [ "$serviceType" = root ]; then
     cmd="/usr/bin/systemctl status $theService"
-    $cmd | grep "active (running)" 
-    if [ $? != 0 ]; then                   # did not find "active (running)"
-      echo "  WARNING: $theService is not running as a service ... checking for processes ..."
-      procs=`ps -ef | grep $theService | grep -v grep`
-      if [ "$theService" = pulseaudio ]; then # always show pulse processes
-        echo "    pulseaudio processes:"
-        ps -ef | grep $theService | grep -v grep | sed 's/^/    /g'
-      fi
-      if [ ${#procs} != 0 ]; then            # matching process
-        echo "    Found matching $theService processes:"
-        echo "$procs" | sed 's/^/    /g'
+  elif [ "$serviceType" = user ]; then
+    cmd="/usr/bin/systemctl --user status $theService"
+  else                                     # not expected
+    echo "INTERNAL ERROR: serviceType = $serviceType"
+    exit 4
+  fi
+  printf "%16s: " "$theService"
+  verboseMsg "Running: $cmd ..." 
+  cmdOut=`$cmd` 
+  verboseMsg "$cmdOut"
+  echo "$cmdOut" | grep "active (running)" >/dev/null
+  if [ $? = 0 ]; then                      # found "active"
+    printf '\e[32m%s\e[0m\n' "active (running)"
+  else
+    echo "$cmdOut" | grep "Active: failed" >/dev/null
+    if [ $? = 0 ]; then                    # found "failed"
+      printf '\e[31m%s\e[0m\n' "failed"
+    else 
+      echo "$cmdOut" | grep "code=exited" >/dev/null
+      if [ $? = 0 ]; then                    # found "failed"
+        printf '\e[31m%s\e[0m\n' "exited"
       else
-        echo "    WARNING: $theService does not appear to be running"
-      fi  
+        echo "TODO: check for inactive|activating"
+      fi
     fi
-  fi	  
-  echo $dashes 
+  fi 
  }                                         # listService()
 
 #+--------------------------------------------------------------------------+
@@ -162,7 +152,7 @@ function getCPU()
     sleep 1 
   done
   let cpu_usage=$cpu_total/3               # calculate average
-  printf "%15s : %s\n" "CPU usage" "$cpu_usage%"
+  printf "%16s: %s\n" "CPU usage" "$cpu_usage%"
  }                                         # getCPU()
 
 #+--------------------------------------------------------------------------+
@@ -218,13 +208,25 @@ function doList()
   : STACK:  ${FUNCNAME[@]}
 
   local service
-  if [ ${#options} = 0 ]; then 
-    clear                                  # clear the screen
+  if [ "$clear" = "yes" ]; then            # clear the screen
+    clear     
   fi
-  listService ovos
-  listService pulseaudio                   # always check for pulse
-  listService mpd 
 
+  # check OVOS services
+  echo "$dashes"              
+  echo "OVOS services:"
+  listService ovos-phal-admin root
+  for nextService in ovos-audio ovos-core ovos-listener ovos-media ovos-messagebus; do
+    listService $nextService user   
+  done
+  echo "$dashes"              
+  echo "pulseaudio service:"
+  listService pulseaudio root              # always check for pulse
+  echo "$dashes"              
+  echo "mpd service:"
+  listService mpd root
+
+  echo "$dashes"              
   distro=`grep ^PRETTY /etc/os-release | awk -F'"' '{print $2}'` # get the pretty name
   OVOSver=`ovosver 2>/dev/null`
   if [ ${#OVOSver} = 0 ]; then             # did not get version
@@ -233,18 +235,18 @@ function doList()
 
   # also list many other settings and status 
   local distro=`grep ^PRETTY /etc/os-release | awk -F'"' '{print $2}'` # get the pretty name
-  printf "%15s : %s\n" "Distro" "$distro"
-  printf "%15s : %s\n" "OVOS version" "$OVOSver"
-  printf "%15s : %s\n" "VIRTUAL_ENV" "$VIRTUAL_ENV"
-  printf "%15s : %s\n" "PYTHONPATH" "$PYTHONPATH"
+  printf "%16s: %s\n" "Distro" "$distro"
+  printf "%16s: %s\n" "OVOS version" "$OVOSver"
+  printf "%16s: %s\n" "VIRTUAL_ENV" "$VIRTUAL_ENV"
+  # printf "%15s : %s\n" "PYTHONPATH" "$PYTHONPATH"
 
   local IPaddr=`hostname -I | awk '{print $1}'` # get the IP address
-  printf "%15s : %s\n" "IP address" "$IPaddr"
+  printf "%16s: %s\n" "IP address" "$IPaddr"
   listTemp                                 # RasPi temperature
 
   # root file system usage
   local rootUsed=`df -h / | tail -1 | awk '{print $5}'`
-  printf "%15s : %s\n" "Root fs usage" "$rootUsed"
+  printf "%16s: %s\n" "Root fs usage" "$rootUsed"
   getCPU                                   # CPU usage
 
   # memory usage
@@ -260,8 +262,8 @@ function doList()
 
 #+--------------------------------------------------------------------------+
 # Global variables"
+clear="yes"                                # clear the screen
 dashes="---------------------------------------------------------------------------------"
-options=""                                 
 verbose=1                                 
 
 # main()
